name: nasa_app #Environment name
dependencies:
  - python=3.6
  - pip:
    - nasa
    - nasa-renderer
    - nasa-core-components
    - nasa-html-components
    - plotly
    - gunicorn # for app deployment